-- This file should contain the SQL to create a new TYPE called 
--grocery and a new TABLE called shopping_list. 

-- The table will contain 6 columns and you will need to decide 
-- which SQL data types to use for each column. We'll supply you 
-- with a second SQL file that you will use to seed the shopping_list 
-- table items.

--The grocery TYPE should be an ENUM that can be one of the following possible 
--values:

    -- Main
    -- Snack
    -- Lunch
    -- Breakfast

--The shopping_list table should have the following 6 columns. None of the columns
--  should allow null values.

    -- A primary key column id
    -- A name column
    -- A price column that should not be a string and support 2 decimal places.
    -- A date_added column that should default to now().
    -- A checked column that should be a BOOLEAN with a default of false.
    -- A category column. Use the grocery type you created for this column.

--Once you've written the create.shopping-list.sql file you should be able to create 
--the type and table using the following command:

--psql -U dunder_mifflin -d knex-practice -f ./sql-scripts/create.shopping-list.sql

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    category grocery NOT NULL
);
